name: e2e-tests
on: [push]
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
      - name: Semantic Release
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}